namespace GoldEx.Shared.DTOs.Settings;

public record GetSettingResponse(
    Guid Id,
    string InstitutionName,
    string Address,
    string PhoneNumber,
    decimal TaxPercent,
    decimal GoldProfitPercent,
    decimal JewelryProfitPercent,
    decimal MoltenGoldCommissionPercent,
    decimal GoldSafetyMarginPercent,
    decimal UsedGoldFinenessDeductionRate,
    decimal GramPerMesghal,
    TimeSpan PriceUpdateInterval,
    bool HasIcon,
    string? InstagramUrl = null,
    string? TelegramUrl = null,
    string? BaleUrl = null,
    string? WhatsAppNumber = null,
    string? AboutText = null,
    string VitrineThemePreset = "royal-emerald",
    string? VitrinePrimaryColor = null,
    string? VitrineAccentColor = null,
    string? VitrineBackgroundColor = null,
    string? VitrineSurfaceColor = null,
    string VitrineCardStyle = "minimal",
    string VitrineRadiusStyle = "rounded",
    string VitrineFontStyle = "iransans",
    string VitrineHeaderStyle = "glass-sticky");